# **Part 1: Theoretical Questions**

## 1. What are the different data structures used in Tensorflow? Give some examples.

Tensorflow is a open-source machine learning framework, uses various data structures to manage the data and model parameters.

1. **Tensors** 

Tensors are multi-dimensional arrays with uniform type.

Examples :

Scalar (0D tensor): tf.constant(3)

Vector (1D tensor): tf.constant([1.0, 2.0, 3.0])

Matrix (2D tensor): tf.constant([[1.0, 2.0], [3.0, 4.0]])

Higher dimensions: tf.constant([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])

2. **Variables**

Variables are special type of data structure used for storing and updating parameters.

Examples :

tf.Variable(3.0)

tf.Variable([1.0, 2.0, 3.0])

3. **Ragged Tensors**

Ragged tensors allows tensors with variable number of elements along some dimensions.

Examples :

tf.ragged.constant([[1, 2, 3], [4, 5], [6, 7, 8, 9]])

4. **String Tensors**

Strings are used to handle string data.

Examples :

tf.constant("Hello, TensorFlow!")

tf.constant(["TensorFlow", "is", "awesome"])

5. **DataFrame**

The 'tf.data' API provides data structure for handling large datasets and evaluation.

Examples:

dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])

dataset = tf.data.Dataset.from_tensor_slices((features, labels))

## 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

* **Tensorflow Constant**

Tensorflow constants are immutable, we can't change the value of it once created.

Typically used for value that do not change during the execution.

Example : tf.constant([1.0, 2.0, 3.0]

* **Tensorflow Variable**

Variables are mutable, we can change the value of it once it created.

Used for value that need to be updated during the execution.

Example : tf.Variable([1.0, 2.0, 3.0]

## 3. Describe the process of matrix addition, multiplication, and elementwise operations in TensorFlow.

Matrix operations like matrix multiplication,addition and elementwise operations are fundamental for various computational operations in machine learning.

* **Matrix Addition**

Matrix addition involves adding corresponding elements of two metrix of same shape.

**Code** :

matrix1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)

matrix2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

matrix_addition = tf.add(matrix1, matrix2)

**Output** : [[ 6.  8.][10. 12.]]

* **Matrix Multiplication**

Matrix multiplication involves multiplying of row of first metrix with column of second metrix and summing the result.

**Code** :

matrix1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)

matrix2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

matrix_multiplication = tf.matmul(matrix1, matrix2)

**Output** : [[19. 22.][43. 50.]]

* **Elementwise Operations**

Elementwise operations involves arithmetic operations on elements of two metrix of same shape.

**Code** :

matrix1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)

matrix2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

elementwise_addition = tf.add(matrix1, matrix2)

elementwise_multiplication = tf.multiply(matrix1, matrix2)

elementwise_division = tf.divide(matrix1, matrix2)

**Output** :

Addition = [[ 6.  8.][10. 12.]]

Multiplication = [[ 5. 12.][21. 32.]]

Division = [[0.2        0.33333334][0.42857143 0.5       ]]

# **Part 2: Practical Implementation**

## Talk 1: Creating and Manipulating Matrices

## 1.Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.

In [3]:
import tensorflow as tf

In [7]:
a = tf.random.normal(shape=(2,2))
print(a)

tf.Tensor(
[[-1.9131193   0.06680815]
 [ 2.0161119   2.2633512 ]], shape=(2, 2), dtype=float32)


## 2.Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix B.

'truncated_normal' function returns the value that are near to zero and it redraws value that are more then two standard deviation of the mean.

In [20]:
x = 5
b = tf.random.truncated_normal([x,x],mean=1,stddev=2)
print(b)

tf.Tensor(
[[ 1.6934111  -0.8560052   0.61431324  2.7056522   0.5779203 ]
 [ 2.397799   -0.754527    1.358814    2.9846075   3.1907222 ]
 [ 0.07629466  2.6631498   1.3831885   0.8095641   0.14195597]
 [-0.75261354  1.1383064  -0.20752275  4.168742    0.06870031]
 [-1.0193453   1.8882385  -1.4627001  -0.720417    3.5183473 ]], shape=(5, 5), dtype=float32)


## 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [21]:
c = tf.random.normal(shape=(2,2),mean=3,stddev=0.5)
print(c)

tf.Tensor(
[[2.2740116 2.3558664]
 [2.9594018 3.2523706]], shape=(2, 2), dtype=float32)


## 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [23]:
a = tf.constant([[1,9],[7,2]])
b = tf.constant([[2,6],[7,4]])
d = tf.add(a,b)
print(d)

tf.Tensor(
[[ 3 15]
 [14  6]], shape=(2, 2), dtype=int32)


## 5.Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [25]:
c = tf.constant([[5,6],[12,9]])
d = tf.constant([[66,20],[7,89]])
e = tf.matmul(c,d)
print(e)

tf.Tensor(
[[ 372  634]
 [ 855 1041]], shape=(2, 2), dtype=int32)


## Talk 2: Performing Additional Matrix Operations

## 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.

In [27]:
f = tf.random.uniform(shape=(2,2),minval=50,maxval=51,dtype=tf.float32)
print(f)

tf.Tensor(
[[50.378662 50.990612]
 [50.617847 50.66206 ]], shape=(2, 2), dtype=float32)


## 2. Calculate the transpose of matrix F and store the result in matrix G.

In [29]:
f = tf.constant([[8,66,52,64,57],[99,71526,85236914710,4,85]])
g = tf.transpose(f)
print(g)

tf.Tensor(
[[          8          99]
 [         66       71526]
 [         52 85236914710]
 [         64           4]
 [         57          85]], shape=(5, 2), dtype=int64)


## 3. Calculate the elementwise exponential of matrix F and store the result in matrix H.

In [11]:
f = tf.constant([[5,10],[9,7]],dtype=tf.float64)
h = tf.exp(f)
print(h)

tf.Tensor(
[[  148.4131591  22026.46579481]
 [ 8103.08392758  1096.63315843]], shape=(2, 2), dtype=float64)


## 4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [17]:
f = tf.constant([[5,6],[1,3]],dtype=tf.float64)
g = tf.constant([[7,5],[2,4]],dtype=tf.float64)

l = tf.concat([f,g],axis=1)
print(l)

tf.Tensor(
[[5. 6. 7. 5.]
 [1. 3. 2. 4.]], shape=(2, 4), dtype=float64)


## 5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [19]:
f = tf.constant([[5,3],[8,6]])
h = tf.constant([[1,2],[4,7]])

j = tf.concat([f,h],axis=0)
print(j)

tf.Tensor(
[[5 3]
 [8 6]
 [1 2]
 [4 7]], shape=(4, 2), dtype=int32)
